


------------------for Native app -------------
--DROP application package STORAGE_INTEGRATION_APP_PKG;
create  application package STORAGE_INTEGRATION_APP_PKG;

---stage creation
create or replace stage APP_STAGE;

list @STORAGE_INTEGRATION_APP_PKG.public.APP_STAGE;


-- REMOVE @STORAGE_INTEGRATION_APP_PKG.PUBLIC.app_stage/native_app/streamlit/readme.md;




--------------copy files from native_app to streamlit ---------------------
COPY FILES INTO @STORAGE_INTEGRATION_APP_PKG.PUBLIC.app_stage/native_app/streamlit/
FROM @STORAGE_INTEGRATION_APP_PKG.PUBLIC.app_stage/native_app/
FILES = ('app.py');



-- Copy app.py to streamlit subfolder
COPY FILES INTO @STORAGE_INTEGRATION_APP_PKG.PUBLIC.app_stage/native_app/streamlit/
FROM @STORAGE_INTEGRATION_APP_PKG.PUBLIC.app_stage/native_app/
FILES = ('environment.yml');



-------------------alter the packages---------------------------------
ALTER APPLICATION PACKAGE STORAGE_INTEGRATION_APP_PKG
  REGISTER VERSION v1
  USING '@STORAGE_INTEGRATION_APP_PKG.PUBLIC.app_stage/native_app';

--removing files
REMOVE @STORAGE_INTEGRATION_APP_PKG.PUBLIC.app_stage/native_app/app.py;
REMOVE @STORAGE_INTEGRATION_APP_PKG.PUBLIC.app_stage/native_app/environment.yml;
REMOVE @CDC_APP_PKG.PUBLIC.MY_STAGE/native_app/streamlit/readme.md;

create application CLOUD_INTEGRATION_APP
from application package STORAGE_INTEGRATION_APP_PKG
using version v1;


------------------droping app 
DROP APPLICATION CLOUD_INTEGRATION_APP CASCADE;



---------------------------grant access for the role ----
GRANT USAGE ON DATABASE BILLING_DB TO APPLICATION STORAGE_INTEGRATION;
GRANT CREATE SCHEMA ON DATABASE BILLING_DB TO APPLICATION STORAGE_INTEGRATION;
GRANT USAGE ON SCHEMA BILLING_DB.CONFIG TO APPLICATION STORAGE_INTEGRATION;
GRANT CREATE TABLE ON SCHEMA BILLING_DB.CONFIG TO APPLICATION STORAGE_INTEGRATION;
GRANT CREATE TABLE ON SCHEMA BILLING_DB.TEST TO APPLICATION STORAGE_INTEGRATION;
GRANT USAGE ON FILE FORMAT BILLING_DB.CONFIG.CSV_TEST_1802 TO APPLICATION STORAGE_INTEGRATION;
GRANT ALL ON TABLE BILLING_DB.CONFIG.INTERATION_INFO TO APPLICATION STORAGE_INTEGRATION;
GRANT ALL ON TABLE BILLING_DB.CONFIG.CDC_CONFIGURATIONS TO APPLICATION STORAGE_INTEGRATION;
GRANT ALL ON SCHEMA BILLING_DB.CONFIG TO APPLICATION STORAGE_INTEGRATION;
GRANT USAGE ON INTEGRATION NATIVE_APP1 TO APPLICATION STORAGE_INTEGRATION;


------------------revoke all access from app role to accountadmin--------
GRANT OWNERSHIP ON ALL STAGES IN DATABASE BILLING_DB TO ROLE ACCOUNTADMIN REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON ALL TABLES IN DATABASE BILLING_DB TO ROLE ACCOUNTADMIN REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE BILLING_DB TO ROLE ACCOUNTADMIN REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON ALL STAGES IN DATABASE BILLING_DB TO ROLE ACCOUNTADMIN REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON ALL STREAMS IN DATABASE BILLING_DB TO ROLE ACCOUNTADMIN REVOKE CURRENT GRANTS;


GRANT OPERATE ON PIPE BILLING_DB.CONFIG.CUSTOMER_PIPE TO APPLICATION STORAGE_INTEGRATION;
GRANT OPERATE ON  PIPE  BILLING_DB.CONFIG.CUSTOMER_PIPE TO ROLE ACCOUNTADMIN ;
GRANT OWNERSHIP ON  PIPE  BILLING_DB.CONFIG.CUSTOMER_PIPE TO ROLE ACCOUNTADMIN  REVOKE CURRENT GRANTS;
ALTER PIPE CUSTOMER_PIPE SET PIPE_EXECUTION_PAUSED=true;

GRANT OPERATE ON PIPE BILLING_DB.CONFIG.POKEMAN_DATA_STAGE TO APPLICATION STORAGE_INTEGRATION;
GRANT OPERATE ON  PIPE  BILLING_DB.CONFIG.POKEMAN_DATA_STAGE TO ROLE ACCOUNTADMIN ;
GRANT OWNERSHIP ON  PIPE  BILLING_DB.CONFIG.POKEMAN_DATA_STAGE TO ROLE ACCOUNTADMIN  REVOKE CURRENT GRANTS;
ALTER PIPE POKEMAN_DATA_STAGE SET PIPE_EXECUTION_PAUSED=true;


-- -- Copy app.py to streamlit subfolder
-- COPY FILES INTO @CDC_APP_PKG.PUBLIC.MY_STAGE/native_app/streamlit/
-- FROM @CDC_APP_PKG.PUBLIC.MY_STAGE/native_app/
-- FILES = ('app.py');

-- COPY FILES INTO @CDC_APP_PKG.PUBLIC.MY_STAGE/native_app/streamlit/
-- FROM @CDC_APP_PKG.PUBLIC.MY_STAGE/native_app/
-- FILES = ('readme.md');

-- -- Copy app.py to streamlit subfolder
-- COPY FILES INTO @CDC_APP_PKG.PUBLIC.MY_STAGE/native_app/streamlit/
-- FROM @CDC_APP_PKG.PUBLIC.MY_STAGE/native_app/
-- FILES = ('environment.yml');

-- Remove old app.py from root (optional)

--my_stage/native_app/environment.yml
REMOVE @STORAGE_INTEGRATION_APP_PKG.PUBLIC.app_stage/native_app/app.py;
REMOVE @STORAGE_INTEGRATION_APP_PKG.PUBLIC.app_stage/native_app/environment.yml;
REMOVE @CDC_APP_PKG.PUBLIC.MY_STAGE/native_app/streamlit/readme.md;


 

-- alter application package CDC_APP_PKG
-- add version v1
-- using '@native_app/native_app/';

ALTER APPLICATION PACKAGE CDC_APP_PKG
  REGISTER VERSION v5
  USING '@CDC_APP_PKG.PUBLIC.MY_STAGE/native_app';

  ALTER APPLICATION CDC_APP_PKG UPGRADE;


  LIST @CDC_APP_PKG.PUBLIC.MY_STAGE;;



create application STORAGE_INTEGRATION
from application package CDC_APP_PKG
using version v5;

DROP APPLICATION CDC_APPV13 CASCADE;

drop application CDC_APPV13;





revoke USAGE ON DATABASE BILLING_DB from APPLICATION CDC_APPv2;
revoke CREATE SCHEMA ON DATABASE BILLING_DB from APPLICATION CDC_APPv2;
revoke USAGE ON SCHEMA BILLING_DB.CONFIG from APPLICATION CDC_APPv2;
revoke CREATE TABLE ON SCHEMA BILLING_DB.TEST from APPLICATION CDC_APPv2;
revoke ALL ON SCHEMA BILLING_DB.CONFIG from APPLICATION CDC_APPv2;
revoke ALL ON TABLE BILLING_DB.CONFIG.INTERATION_INFO from APPLICATION CDC_APPv2;


DROP TABLE BILLING_DB.TEST.INTERATION_INFO;

DROP TABLE BILLING_DB.TEST.CDC_CONFIGURATIONS;

GRANT CREATE INTEGRATION ON ACCOUNT TO APPLICATION CDC_APPv5;
-- Consumer runs this directly
GRANT CREATE INTEGRATION ON ACCOUNT TO APPLICATION CDC_APPV3;


select * from BILLING_DB.CONFIG.CDC_CONFIGURATIONS;


GRANT USAGE ON DATABASE BILLING_DB TO APPLICATION CDC_APPV13;
GRANT CREATE SCHEMA ON DATABASE BILLING_DB TO APPLICATION CDC_APPV13;
GRANT USAGE ON SCHEMA BILLING_DB.CONFIG TO APPLICATION CDC_APPV13;
GRANT CREATE TABLE ON SCHEMA BILLING_DB.CONFIG TO APPLICATION CDC_APPV13;
GRANT CREATE TABLE ON SCHEMA BILLING_DB.TEST TO APPLICATION CDC_APPV13;
GRANT USAGE ON FILE FORMAT BILLING_DB.CONFIG.CSV_TEST_1802 TO ROLE CDC_APPV13;



GRANT ALL ON TABLE BILLING_DB.CONFIG.INTERATION_INFO TO APPLICATION CDC_APPV13;
GRANT ALL ON TABLE BILLING_DB.CONFIG.CDC_CONFIGURATIONS TO APPLICATION CDC_APPV13;
GRANT ALL ON SCHEMA BILLING_DB.CONFIG TO APPLICATION CDC_APPV13;
GRANT USAGE ON INTEGRATION NATIVE_APP1 TO APPLICATION CDC_APPV13;


GRANT USAGE ON DATABASE BILLING_DB TO APPLICATION STORAGE_INTEGRATION;
GRANT CREATE SCHEMA ON DATABASE BILLING_DB TO APPLICATION STORAGE_INTEGRATION;
GRANT USAGE ON SCHEMA BILLING_DB.CONFIG TO APPLICATION STORAGE_INTEGRATION;
GRANT CREATE TABLE ON SCHEMA BILLING_DB.CONFIG TO APPLICATION STORAGE_INTEGRATION;
GRANT CREATE TABLE ON SCHEMA BILLING_DB.TEST TO APPLICATION STORAGE_INTEGRATION;
GRANT USAGE ON FILE FORMAT BILLING_DB.CONFIG.CSV_TEST_1802 TO APPLICATION STORAGE_INTEGRATION;
GRANT ALL ON TABLE BILLING_DB.CONFIG.INTERATION_INFO TO APPLICATION STORAGE_INTEGRATION;
GRANT ALL ON TABLE BILLING_DB.CONFIG.CDC_CONFIGURATIONS TO APPLICATION STORAGE_INTEGRATION;
GRANT ALL ON SCHEMA BILLING_DB.CONFIG TO APPLICATION STORAGE_INTEGRATION;
GRANT USAGE ON INTEGRATION NATIVE_APP1 TO APPLICATION STORAGE_INTEGRATION;




------------revoke------------------
revoke USAGE ON DATABASE BILLING_DB from APPLICATION CDC_APPV11;
revoke CREATE SCHEMA ON DATABASE BILLING_DB from APPLICATION CDC_APPV11;
revoke USAGE ON SCHEMA BILLING_DB.CONFIG from APPLICATION CDC_APPV11;
revoke CREATE TABLE ON SCHEMA BILLING_DB.CONFIG from APPLICATION CDC_APPV11;
revoke ALL ON TABLE BILLING_DB.CONFIG.INTERATION_INFO from APPLICATION CDC_APPV11;
revoke ALL ON SCHEMA BILLING_DB.CONFIG from APPLICATION CDC_APPV11;

-- These go to APPLICATION (not application role)
GRANT CREATE DATABASE ON ACCOUNT TO APPLICATION CDC_APPV11;
GRANT CREATE INTEGRATION ON ACCOUNT TO APPLICATION CDC_APPV11;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO APPLICATION CDC_APPV11;

-- Database/schema access
GRANT USAGE ON DATABASE BILLING_DB TO APPLICATION CDC_APPV3;
GRANT CREATE SCHEMA ON DATABASE BILLING_DB TO APPLICATION CDC_APPV3;
GRANT ALL ON SCHEMA BILLING_DB.CONFIG TO APPLICATION CDC_APPV3;

GRANT USAGE ON INTEGRATION S3_BEATROTE_INTEGRATION  TO APPLICATION CDC_APPV11;
GRANT CREATE INTEGRATION ON ACCOUNT TO APPLICATION CDC_APPV11;
-- Consumer runs this directly
GRANT CREATE INTEGRATION ON ACCOUNT TO APPLICATION CDC_APPV3;


select * from 

-- drop  application CDC_APPv2;


ALTER APPLICATION PACKAGE CDC_APP_PKG
  ADD PATCH FOR VERSION v1
  USING '@CDC_APP_PKG.PUBLIC.MY_STAGE/native_app';

ALTER APPLICATION CDC_APP UPGRADE;

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO APPLICATION CDC_APP1;

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO APPLICATION CDC_APP;


drop application CDC_APP;

show integrations;

desc integration NATIVE_APP1;

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO APPLICATION CDC_APP;

-- In setup.sql
CREATE OR REPLACE VIEW app_schema.database_details AS
SELECT * FROM INFORMATION_SCHEMA.SCHEMATA;


-- Grant access to SNOWFLAKE database for ACCOUNT_USAGE
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO APPLICATION CDC_APP;

-- If your app needs to create/use external database
CREATE DATABASE IF NOT EXISTS CDC_APP_DB;
GRANT USAGE ON DATABASE CDC_APP_DB TO APPLICATION CDC_APP;
GRANT CREATE SCHEMA ON DATABASE CDC_APP_DB TO APPLICATION CDC_APP;
GRANT ALL ON DATABASE CDC_APP_DB TO APPLICATION CDC_APP;


ALTER APPLICATION CDC_APP_V2 UPGRADE USING VERSION v1;

GRANT USAGE ON INTEGRATION S3_INT TO APPLICATION CDC_APP;
GRANT USAGE ON DATABASE SNOWFLAKE TO APPLICATION CDC_APP;
GRANT USAGE ON SCHEMA BILLING_DB.CONFIG TO APPLICATION CDC_APP;



DROP APPLICATION CDC_APP_V2;

CREATE APPLICATION CDC_APP_V2
FROM APPLICATION PACKAGE CDC_APP_PKG
USING VERSION v1;


ALTER APPLICATION PACKAGE CDC_APP_PKG
  REGISTER VERSION v2
  USING '@CDC_APP_PKG.PUBLIC.MY_STAGE/native_app';

ALTER APPLICATION CDC_APP_V2 UPGRADE USING VERSION v2;








CREATE STREAMLIT app_schema.cdc_manager
MAIN_FILE = 'app.py';



grant create stage on schema <db>.<schema> to application role APP_ROLE;
grant create pipe on schema <db>.<schema> to application role APP_ROLE;
grant create stream on schema <db>.<schema> to application role APP_ROLE;
grant create task on schema <db>.<schema> to application role APP_ROLE;
grant create table on schema <db>.<schema> to application role APP_ROLE;




select * from billing_db.information_schema.file_formats;


SHOW APPLICATIONS;


GRANT USAGE
ON INTEGRATION my_storage_integration
TO APPLICATION CDC_APP;
